# OpenShift specific overrides for agent collector
# These settings will be merged with agent-collector-base.yaml

receivers:
  kubeletstats:
    collection_interval: 10s
    auth_type: serviceAccount
    endpoint: "https://${env:K8S_NODE_NAME}:10250"
    ca_file: /etc/kubelet-serving-ca/ca-bundle.crt
    metric_groups:
      - container
      - pod
      - node
      - volume
    extra_metadata_labels:
      - container.id
    
  # OpenShift uses CRI-O container runtime  
  filelog:
    include:
      - "/var/log/pods/*/*/*.log"
      - "/var/log/containers/*.log"
    exclude:
      - "/var/log/pods/openshift-*/*/*.log"  # Skip OpenShift system logs
      - "/var/log/pods/kube-*/*/*.log"       # Skip kube-system logs
      - "/var/log/pods/*/otc-container/*.log"
    start_at: end
    include_file_path: true
    include_file_name: false
    operators:
      - type: router
        id: get-format
        routes:
          - output: parser-crio
            expr: 'body matches "^[^ Z]+ "'
          - output: parser-docker
            expr: 'body matches "^\\{"'
      - type: json_parser
        id: parser-docker
        if: 'attributes["log_type"] == "docker"'
      - type: regex_parser
        id: parser-crio
        if: 'attributes["log_type"] == "crio"'
        regex: '^(?P<time>[^ Z]+) (?P<stream>stdout|stderr) (?P<logtag>[^ ]*) (?P<message>.*)$'
        timestamp:
          parse_from: attributes.time
          layout: '%Y-%m-%dT%H:%M:%S.%LZ'

processors:
  resourcedetection:
    # OpenShift resource detector will add cloud provider attributes automatically
    detectors: ["env", "system", "k8snode", "openshift"]
    timeout: 5s
    
  k8sattributes:
    auth_type: serviceAccount
    passthrough: false
    filter:
      node_from_env_var: K8S_NODE_NAME
    extract:
      metadata:
        - "k8s.namespace.name"
        - "k8s.deployment.name"
        - "k8s.statefulset.name"
        - "k8s.daemonset.name"
        - "k8s.cronjob.name"
        - "k8s.job.name"
        - "k8s.node.name"
        - "k8s.pod.name"
        - "k8s.pod.uid"
        - "k8s.pod.start_time"
    pod_association:
      - sources:
          - from: resource_attribute
            name: "k8s.pod.ip"
      - sources:
          - from: resource_attribute
            name: "k8s.pod.uid"
      - sources:
          - from: connection